// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhlrXCQveUpSBAaneDmmJYaCKRy4ABFmM',
    appId: '1:381972257384:web:af4abea058e69e83e5f9dd',
    messagingSenderId: '381972257384',
    projectId: 'ezlife-7b7fc',
    authDomain: 'ezlife-7b7fc.firebaseapp.com',
    storageBucket: 'ezlife-7b7fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcWkUoyV53DYmgUd9jfoPVAbC8x0Qpx2E',
    appId: '1:381972257384:android:7507b76fa07032fde5f9dd',
    messagingSenderId: '381972257384',
    projectId: 'ezlife-7b7fc',
    storageBucket: 'ezlife-7b7fc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhlrXCQveUpSBAaneDmmJYaCKRy4ABFmM',
    appId: '1:381972257384:web:c9c65f22f766e73ee5f9dd',
    messagingSenderId: '381972257384',
    projectId: 'ezlife-7b7fc',
    authDomain: 'ezlife-7b7fc.firebaseapp.com',
    storageBucket: 'ezlife-7b7fc.appspot.com',
  );
}
